#!/usr/bin/python
# -*- coding: utf-8 -*
import cgi
import cgitb
cgitb.enable()
import random


d = {'histone methylation':'组织蛋白甲基化',
     'methylated histone binding':'组蛋白甲基化绑定',
     'methyltransferase activity':'甲基转移酶活性',
     'S-adenosylmethionine-dependent methyltransferase activity':'依赖S腺苷甲硫氨酸的甲基转移酶活性',
     'vernalization response':'应对春化',
     'regulation of gene expression by genetic imprinting':'遗传印迹基因表达调控',
     'regulation of gene expression':'基因表达调控',
     'regulation of gene expression, epigenetic':'基因表达调控，表观遗传',
     'epigenetic':'表观遗传',
     'negative regulation of flower development':'逆向调控花发育',
     'positive regulation of flower development':'正向调控花发育',     
     'DNA binding':'绑定DNA',
     'protein binding':'绑定蛋白',
     'nucleus':'细胞核',
     'sequence-specific DNA binding transcription factor activity':'特定序列DNA绑定 转录因子活动',
     'sequence-specific DNA binding':'特定序列DNA绑定',     
     'response to absence of light':'应对缺光环境',
     'chloroplast':'叶绿体',
     'negative':'负',
     'regulation':'调控',
     'chitin':'甲壳素',
     'defense response to fungus':'防卫真菌',
     'defense response to bacterium':'防卫细菌',
     'defense response to oomycetes':'防卫卵菌反应',
     'zinc ion binding':'绑定锌离子',
     'zinc ion':'锌离子',
     'zinc':'锌',     
     'hydrogen peroxide':'过氧化氢',
     'metabolic':'新陈代谢',
     'process':'过程',
     'processing':'处理',
     'molecule':'分子',
     'bacterial origin':'细菌源',
     'signaling pathway':'信道',
     'signaling':'发信号',
     'external stimulus':'外激',
     'detection of external stimulus':'外激探测',
     'binding':'绑定',
     'pathway':'路径',
     'root development':'根生长',
     'root':'根',
     'root cap':'根冠',
     'biosynthetic process,':'生物合成，',
     'biosynthetic process':'生物合成',
     'catalytic activity':'催化活性',
     'isopentenyl diphosphate':'二甲丙烯基二磷酸（C<sub>5</sub>H<sub>12</sub>O<sub>7</sub>P<sub>2</sub>）',
     'sterol':'固醇',
     'mevalonate':'甲羟戊酸',
     '4-phosphate':'4磷酸',
     'mitochondrion':'线粒体',
     'mitochondrion localization':'线粒体固定',
     'mitochondrion organization':'线粒体组织',
     'localization':'固定',     
     'mitochondrial':'线粒体',
     'mitochondrial envelope':'线粒体封套',
     'mitochondrial intermembrane space':'线粒体膜间空间',
     'mitochondrial electron transport, NADH to ubiquinone':'线粒体电子运输，脱氢酶变到泛醌',
     'mitochondrial electron transport, succinate to ubiquinone':'线粒体电子运输，琥珀酸变到泛醌',
     'electron':'电子',
     'methylerythritol':'甲基赤',
     'Golgi apparatus':'高尔基体',
     'vacuole':'液泡',
     'plasmodesma':'原生质丝',
     'plasma membrane':'细胞膜',
     'actin nucleation':'肌动蛋白核化',
     'actin':'肌动蛋白',
     'cell wall':'细胞壁',
     'cell wall organization':'细胞壁组织',
     'root hair':'根毛',
     'root hair cell':'根毛细胞',
     'cell differentiation':'细胞变型',
     'cell division':'细胞分裂',
     'differentiation':'变型',
     'cell':'细胞',
     'cellular':'细胞',
     'cell adhesion':'细胞依附',
     'trichome morphogenesis':'毛状体成型',
     'trichome branching':'毛状体分支',
     'trichome':'毛状体',
     'biological_process':'--',
     'negative regulation of biological process':'生物过程逆向调控',
     'cellular_component':'--',
     'cytoplasm':'细胞质',
     'cytosol':'胞浆',
     'protein':'蛋白质',
     'N-linked':'N链',
     'N-glycan':'N聚糖',
     'glycosylation':'醣基化',
     'transcription,':'转录，',
     'transcription':'转录',
     'DNA-templated':'以DNA为模版',
     'aldo-keto reductase (NADP) activity':'醛酮还原酶活性',
     'positive':'正',
     'catabolic':'分解代谢',
     'nuclear-transcribed':'核内转录',
     'nuclear body':'核小体',
     'nuclear chromatin':'核染色质',
     'xenobiotic stimulus':'异物刺激',
     'response':'应对',
     'response to xenobiotic stimulus':'应对异物刺激',
     'nucleotide':'核苷酸',
     'gravitropism':'向地性',
     'chromatin':'染色质',
     'chromatin remodeling':'重塑染色质',
     'chromatin silencing by small RNA':'小RNA引起的染色质静默',
     'malate':'苹果酸',
     'chromatin silencing':'染色质静默',     
     'xylan':'木聚糖',
     'interference':'干扰',
     'chromatid cohesion':'染色单体凝聚',
     'glucuronoxylan':'葡糖醛酸木聚糖',
     'silencing':'静默',
     'methylation-dependent':'甲基化依赖',
     'meiotic':'减数分裂',
     'chromosome':'染色体',
     'segregation':'隔离',
     'E3 ubiquitin ligase complex':'泛素连接酶',
     'ubiquitin ligase complex':'泛素连接酶',
     'ligase activity':'连接酶活性',
     'ligase':'连接酶',
     'SCF ubiquitin ligase complex':'针对蛋白酶体降解的泛素连接酶',     
     'Cul4-RING':'Cul4环',
     'helicase activity':'螺旋酶活性',
     'ATP binding':'绑定三磷酸腺苷',
     'response to salt stress':'应对盐压',
     'methionine':'蛋氨酸',
     'RNA splicing,':'RNA剪接，',
     'virus induced':'病毒引起的',
     'gene':'基因',
     'multicellular organismal development':'多细胞有机体生长',
     'vegetative':'营养生长',
     'ethylene-activated':'乙烯激活',
     'cascade':'<a title=cascade>信号中继</a>',
     'endoplasmic reticulum':'内质网',
     'signal recognition particle,':'信号识别粒子，',
     'recognition':'识别',
     'particle':'粒子',
     'endocytosis':'内吞作用',
     'unfolded':'展开',
     'protein targeting to membrane':'瞄准细胞膜的蛋白',
     'protein targeting to chloroplast':'瞄准叶绿体的蛋白',     
     'jasmonic acid mediated':'由茉莉酸引发的',
     'abscisic acid':'脱落酸',
     'abscisic acid-activated':'脱落酸激活的',
     'response to cold':'应对冷冻',
     'cellular response to cold':'细胞应对冷冻',     
     'signal transduction':'信号传递',
     'intracellular signal transduction':'细胞间信号传递',
     'programmed cell death':'计划内细胞死亡',
     'cell death':'细胞死亡',     
     'plant-type hypersensitive':'植物过敏',
     'plant-type':'植物',     
     'systemic acquired resistance,':'系统获得抵御，',
     'systemic acquired resistance, salicylic acid mediated signaling pathway':'系统获得抵御，由水杨酸引发的信道',
     'salicylic acid':'水杨酸',
     'salicylic acid mediated':'由水杨酸引发的',
     'heat acclimation':'高温适应',
     'acclimation':'适应',     
     'ethylene':'乙烯',
     'defense':'防卫',
     'respiratory burst involved in defense response':'防卫急促呼吸',
     'communication':'通信',
     'integral component of endoplasmic reticulum membrane':'内质网膜构件',
     'integral component of cytoplasmic side of endoplasmic reticulum membrane':'内质网膜细胞质边界构件',
     'endoplasmic reticulum membrane':'内质网膜',
     'stress':'压',
     'ER-nucleus':'内质网与细胞核间',
     'ER-associated ubiquitin-dependent protein':'与内质网关联且依赖泛素的蛋白',
     'high light intensity':'强光',
     'kinase':'激酶',     
     'systemic acquired resistance':'系统抵御',
     'detection of biotic stimulus':'检测生物刺激',
     'nucleosome':'核小体',
     'nucleolus':'核仁',
     'assembly':'组装',
     'DNA mediated transformation':'由DNA引发的变形',
     'extracellular region':'细胞外区域',
     'cysteine-type endopeptidase inhibitor activity':'半胱氨酸类内肽酶抑制剂活性',
     'serine-type endopeptidase inhibitor activity':'丝氨酸类内肽酶抑制剂活性',     
     'chloroplastic endopeptidase Clp complex':'叶绿体内肽酶（催化水解蛋白质为小肽）',
     'molecular_function':'--',
     'gibberellic acid mediated':'由赤酶酸引发的',
     'terpenoid':'类萜化合物',
     'gibberellin':'赤酶素',
     'organization':'成型',
     'organelle organization':'细胞器成型',
     'intracellular membrane-bounded organelle':'细胞内部被膜包裹的细胞器',
     'organ morphogenesis':'器官成型',
     'macromolecule':'高分子',
     'biogenesis':'产生',
     'tissue development':'组织生发',
     'folding':'折叠',
     'cellular response to heat':'细胞应对热',     
     'response to heat':'应对热',
     'seed maturation':'种子成熟',
     'targeting to':'对准',
     'cellular response to starvation':'应对饥饿',
     'vesicle-mediated transport':'由囊泡引发的运输',
     'vesicle-mediated':'由囊泡引发的',     
     'plasmodesmata-mediated':'由胞间连丝引发的',     
     'heterodimerization activity':'异源二聚体成型活动',
     'sequence-specific':'特定序列',
     'ubiquitin-protein transferase activity':'泛素蛋白转移酶活性',
     'transferase':'转移酶',
     'oxidative stress':'氧化压力',
     'hyperosmotic':'高渗',
     'water deprivation':'失水',
     'water transport':'运水',     
     'cobalt ion':'钴离子',
     'phosphatidylinositol':'磷脂酰肌醇',
     'auxin':'生长素',
     'auxin mediated signaling pathway involved in phyllotactic patterning':'叶序图案形成中生长素引导的信道',
     'leaf senescence':'叶片衰老',
     'leaf':'叶片',     
     'salinity':'盐份',
     'seed dormancy':'种子冬眠',
     'sugar mediated':'由糖引发的',
     'response to wounding':'应对受伤',
     'protein histidine kinase binding':'蛋白质组氨酸激酶绑定',
     'histidine':'组氨酸',
     'phosphotransfer':'磷酸转移',
     'phenylalanine':'苯丙氨酸',
     'tripeptide transport':'三肽运输',
     'leucine':'亮氨酸',
     'jasmonic acid':'茉莉酸',
     'dipeptide transport':'二肽运输',
     'oligopeptide transport':'寡肽运输',
     'oligopeptide':'寡肽',
     'tripeptide transporter activity':'三肽运输活性',
     'dipeptide transporter activity':'二肽运输活性',
     'peptide':'肽',
     'transporter activity':'运输员活性',
     'membrane':'细胞膜',
     'photomorphogenesis':'光调节生长',
     'photoinhibition':'光抑制',
     'ubiquitination':'泛素化',
     'response to freezing':'应对冷冻',
     'embryo development':'胚胎发育',
     'seed germination':'种子发芽',
     'meristem':'分生组织',
     'meristem structural organization':'分生组织结构调整',
     'flower development':'花发育',
     'flower morphogenesis':'花成型',     
     'seed development':'种子发育',
     'lipid':'脂质',
     'storage':'存储',
     'chloroplast':'叶绿体',
     'chloroplast photosystem':'叶绿体光系统',
     'chloroplast membrane':'叶绿体膜',
     'chloroplast stroma':'叶绿体基质',
     'chloroplast thylakoid membrane':'叶绿体类囊体膜',
     'chloroplast thylakoid':'叶绿体类囊体',
     'chloroplast stromal thylakoid':'叶绿体间质类囊体',
     'chloroplast envelope':'叶绿体封套',
     'plastid envelope':'质体封套',
     'chloroplast ATP synthase complex':'叶绿体三磷酸腺苷合成酶复合体',
     'translational elongation':'转译伸长',
     'triplet codon-amino acid adaptor activity':'三联密码子氨基酸适配器活动',
     'vacuolar membrane':'液泡膜',
     'cytosolic ribosome':'胞质核糖体',
     'translation':'转译',
     'ubiquitin-dependent protein catabolic process':'泛素依赖蛋白质分解过程',
     'protein phosphorylation':'蛋白磷酸化',
     '6-phosphofructokinase':'六磷酸果糖激酶',
     'photosystem I assembly':'一号光系统组装',
     'photosystem I reaction center':'一号光系统反应中心',
     'photosystem II assembly':'二号光系统组装',
     'photosystem II repair':'二号光系统维修',
     'photosystem II oxygen evolving complex':'二号光系统放氧复合物',
     'peroxisome':'过氧化物酶体',
     'histone H3-K9 methylation':'组蛋白H3-K9甲基化',
     'histone H3-K9 dimethylation':'组蛋白H3-K9去甲基化',     
     'trans-Golgi network':'反式高尔基网',
     'syncytium':'合胞体',
     'embryo development ending in seed dormancy':'种子冬眠导致胚胎发育结束',
     'response to cadmium ion':'应对镉离子',
     'glycolytic process':'糖酵解过程',
     'cytosolic small ribosomal subunit':'胞浆小核糖体亚基',
     'small ribosomal subunit':'小核糖体亚基',
     'mitochondrial small ribosomal subunit':'线粒体小核糖体亚基',
     'reciprocal meiotic recombination':'相互减数分裂重组',
     'meiotic mismatch repair':'减数分裂误配维修',
     'plastoglobule':'叶绿体内脂蛋白球',
     'pollen tube growth':'花粉管生长',
     'pollen tube growth':'花粉管发育',
     'pollen':'花粉',
     'pollen wall':'花粉壁',
     'jasmonic acid mediated signaling pathway':'由茉莉酸引发的信道',
     'protein ubiquitination involved in ubiquitin-dependent protein catabolic process':'蛋白质分解过程中蛋白泛素化',
     'protein ubiquitination':'蛋白泛素化',
     'endoplasmic reticulum unfolded protein response':'内质网展开蛋白应对',
     'response to abscisic acid':'应对脱落酸',
     'cytosolic large ribosomal subunit':'胞质核糖体大亚基',
     'DNA methylation':'DNA甲基化',
     'protein serine/threonine kinase activity':'蛋白质 丝氨酸/苏氨酸激酶活性',
     'protein serine/threonine kinase regulator activity':'蛋白质 丝氨酸/苏氨酸激酶调控者活性',
     'serine':'丝氨酸',
     'transferase activity, transferring glycosyl groups':'转移酶活性，转移糖基组',
     'negative regulation of transcription, DNA-templated':'转录逆向调控，DNA模板',
     'DNA repair':'维修DNA',
     'toxin catabolic process':'分解毒素',
     'protein autophosphorylation':'自磷酸化蛋白',
     'N-terminal protein myristoylation':'氨组（-NH<sub>2</sub>）结尾蛋白添加肉豆蔻酰组',
     'anchored component of membrane':'细胞膜锚定成分',
     'GPI anchor':'糖基磷脂酰肌醇',
     'response to chitin':'应对甲壳素',
     'late endosome':'次级内体',
     'endosome':'内体',
     'methylation-dependent chromatin silencing':'依赖甲基化的染色质静默',
     'isopentenyl diphosphate biosynthetic process, methylerythritol 4-phosphate pathway':'异戊烯基二磷酸合成，甲基赤4磷酸路径',
     'photosynthesis, light reaction':'光合作用，光反应',
     'rRNA processing':'rRNA处理',
     'chloroplast thylakoid lumen':'叶绿体类囊体腔',
     'mitochondrial respiratory chain complex':'线粒体呼吸链复合物',
     'respiratory chain complex':'呼吸链复合物',
     'response to auxin':'应对生长素',
     'apoplast':'质外体',
     'thylakoid membrane organization':'组成类囊体膜',
     'cysteine biosynthetic process':'半胱氨酸合成',
     'salicylic acid biosynthetic process':'水杨酸合成',
     'photosynthesis':'光合作用',
     'regulation of protein dephosphorylation':'调控蛋白去磷酸化',
     'dephosphorylation':'去磷酸化',
     'defense response':'防卫应对',
     'defense response to':'防卫应对',
     'starch biosynthetic process':'淀粉合成',
     'starch':'淀粉',
     'thylakoid':'类囊体',
     'structural constituent of ribosome':'核糖体的结构成分',
     'structural constituent of cytoskeleton':'细胞骨架的结构成分',
     'cytoskeleton':'细胞骨架',
     'structural molecule activity':'结构分子活性',
     'GTP binding':'绑定三磷酸鸟苷',
     'protein kinase activity':'蛋白激酶活性',
     'DNA-templated transcription, elongation':'转录，RNA分子伸长',
     'glucosinolate biosynthetic process':'硫代葡萄糖甙合成',
     'glucosinolate':'硫代葡萄糖甙合成',
     'glucosyltransferase':'葡萄糖糖基转移酶',
     '3-O-glucosyltransferase':'3-O-葡萄糖糖基转移酶',
     'UDP-glucosyltransferase':'尿苷5\'二磷酸葡萄糖糖基转移酶',
     '7-O-glucosyltransferase':'7-O-葡萄糖糖基转移酶',
     'UDP':'尿苷二磷酸',
     'flavonol':'黄酮醇',
     'histone lysine methylation':'组蛋白赖氨酸甲基化',
     'fatty acid beta-oxidation':'脂肪酸β氧化',
     'fatty acid':'脂肪酸',
     'xylan biosynthetic process':'木聚糖合成',
     'regulation of hydrogen peroxide metabolic process':'调控过氧化氢代谢过程',
     'root hair elongation':'根毛伸长',
     'root hair initiation':'根毛初长成',
     'response to endoplasmic reticulum stress':'应对内质网压',
     'photorespiration':'光呼吸',
     'DNA endoreduplication':'DNA核内复制',
     'RNA binding':'RNA绑定',
     'pentose-phosphate shunt':'戊糖磷酸分流',
     'Golgi organization':'组成高尔基体',
     'metabolic process':'新陈代谢过程',
     'plant-type cell wall modification':'植物细胞壁改动',
     'RNA methylation':'RNA甲基化',
     'methylation':'甲基化',     
     'proteasome-mediated ubiquitin-dependent protein catabolic process':'蛋白质分解（由蛋白酶体引发并且依赖泛素）',
     'hyperosmotic salinity response':'高渗盐应对',
     'protein targeting to mitochondrion':'瞄准线粒体的蛋白质',
     'salicylic acid mediated signaling pathway':'由水杨酸引发的信道',
     'chloroplast organization':'组织叶绿体',
     'regulation of DNA replication':'调控DNA复制',
     'mitochondrial inner membrane':'线粒体内膜',
     'mitochondrial membrane':'线粒体膜',     
     'response to osmotic stress':'应对渗透压',
     'plastid':'质体',
     'cullin deneddylation':'疏水蛋白脱去泛素状蛋白质<a href=\"http://en.wikipedia.org/wiki/Neddylation\">NEDD8</a>',
     'proteolysis':'蛋白水解作用',
     'nucleic acid binding':'绑定核酸',
     'vegetative to reproductive phase transition of meristem':'分生组织由营养结构转变为生殖结构',
     'regulation of timing of transition from vegetative to reproductive phase':'调控由营养结构转变为生殖结构时机的时机',
     'regulation of flower development':'调控花发育',
     'protein import into peroxisome matrix':'引入蛋白到过氧化物酶体矩阵',
     'plant-type cell wall':'植物型细胞壁',
     'DNA replication':'复制DNA',
     'transcription from plastid promoter':'从质体启动带转录',
     'response to jasmonic acid':'应对茉莉酸',
     'jasmonic acid biosynthetic process':'茉莉酸合成过程',
     'double-strand break repair via homologous recombination':'通过同源重组修复双链',
     'double-strand break repair via synthesis-dependent strand annealing':'通过依赖合成的温控变性修复双链？？？',
     'microtubule cytoskeleton organization':'组织微管骨架',
     'root hair cell differentiation':'根毛细胞变型',
     'sister chromatid cohesion':'姐妹染色单体凝聚',
     'meiotic DNA double-strand break formation':'减数分裂DNA双链断开',
     'photoperiodism, flowering':'光周期，开花',
     'photoperiodism':'光周期',     
     'RNA processing':'RNA处理',
     'proteasomal protein catabolic process':'蛋白酶体分解代谢蛋白质',
     'unidimensional cell growth':'细胞线性生长',
     'cell growth':'细胞生长',     
     'post-translational protein modification':'转译后期蛋白质改造',
     'posttranscriptional':'转译后期',
     'embryo sac egg':'胚囊蛋',
     'embryo sac':'胚囊',     
     'via endonucleolytic cleavage and ligation':'通过核苷酸链分割与衔接',
     'endonucleolytic cleavage involved in rRNA processing':'rRNA处理中核苷酸链分割',
     'negative regulation of defense response':'逆向调控防卫反应',
     'production of miRNAs involved in gene silencing by miRNA':'基因静默微RNA制造',
     'telomere maintenance in response to DNA damage':'应对DNA破损中端粒保养',
     'DNA damage stimulus':'DNA破损刺激',
     'maintenance':'保养',
     'pyrimidine ribonucleotide':'嘧啶核苷酸',
     'pollen exine formation':'构造花粉外壁',
     'chlorophyll':'叶绿素',
     'chloroplast inner membrane':'叶绿体内膜',
     'protein desumoylation':'蛋白质脱去小泛素样蛋白（SUMO）',
     'plant-type vacuole membrane':'植物液泡膜',
     'production of ta-siRNAs involved in RNA interference':'制造参与RNA干扰的<a title=\"ta-siRNA\">跨分子siRNA</a>',
     'histone modification':'组织蛋白改造',
     'mRNA splicing, via spliceosome':'<a title=\"mRNA\">通信RNA</a>剪接，通过剪接体',
     'spliceosomal complex':'剪接复合体',
     'ATPase activity, coupled to transmembrane movement of substances':'三磷酸腺苷酶活性，耦合跨膜物质移动',
     'ATPase activity, coupled to transmembrane movement of ions, phosphorylative mechanism':'三磷酸腺苷酶活性，耦合跨膜离子移动，磷酸化机制',
     'cytokinin-activated':'由细胞分裂素激活的',
     'oxygen binding':'绑定氧',
     'cellular response to iron ion starvation':'铁离子缺乏的细胞应对',
     'iron ion':'铁离子',
     'response to sucrose':'应对蔗糖',
     'calmodulin binding':'绑定钙调蛋白',
     'heterotrimeric G proteins':'异三聚体G蛋白',
     'indoleacetic acid':'吲哚乙酸',
     'cytoskeleton organization':'组织骨架',
     'ribosome':'核糖体',
     'regulation of telomere maintenance':'调控端粒养护',
     'iron-sulfur cluster assembly':'组装铁硫簇',
     'sulfotransferase':'磺基转移酶',
     'double-strand break repair':'修复双链',
     'double-strand break':'双链断开',
     'double-stranded':'双链',
     'meiotic chromosome segregation':'减数分裂染色体分离',
     'nitrate':'硝酸',
     'nitric oxide':'一氧化氮',
     'transport':'运输',
     'copper ion binding':'绑定铜离子',
     'copper ion':'铜离子',
     'cellular response to':'细胞应对',
     'gene silencing':'基因静默',
     'leaf morphogenesis':'叶成型',
     'plant-type cell wall organization':'组建植物细胞壁',
     'galactolipid':'半乳糖',
     'DNA replication initiation':'初始化DNA复制',
     'mRNA modification':'mRNA改造',
     'carotenoid':'类胡萝卜素',
     'response to bacterium':'应对细菌',
     'pollen development':'花粉发育',
     'gene silencing by RNA':'RNA引起的基因静默',
     'regulation of':'调控',
     'chromosome organization':'组建染色体',
     'methylglyoxal catabolic process to D-lactate':'甲基乙二醛代谢为D乳酸',
     'methylglyoxal':'甲基乙二醛',
     'D-lactate':'D乳酸',
     'catabolic process':'分解过程',
     'mRNA':'通信RNA',
     'cytokinesis':'胞质分裂',
     'cytokinesis by cell plate formation':'胞质分裂，单元板形成',
     'methionine':'蛋氨酸',
     'vesicle-mediated':'囊泡引发的',
     'vesicle':'囊泡',
     'hyperosmotic response':'高渗应对',
     'hydrolase activity, hydrolyzing O-glycosyl compounds':'水解酶活性，水解O型糖基化合物',
     'hydrolase activity, acting on ester bonds':'水解酶活性，作用于酯键',
     'hydrolase':'水解酶',
     'O-glycosyl':'O型糖基',
     'compounds':'化合物',
     'misfolded protein':'误卷蛋白',
     'calcium ion':'钙离子',
     'light stimulus':'光刺激',
     'stimulus':'刺激',
     'cell proliferation':'细胞增殖',
     'circadian rhythm':'昼夜规律',
     'chloroplast outer membrane':'叶绿体外膜',
     'cellulose':'纤维素',
     'defense response, incompatible interaction':'防卫应答，相互作用冲突',
     'synapsis':'减数分裂时同源染色体配对',
     'mRNA export from nucleus':'细胞核输出通信RNA',
     'cell tip growth':'细胞顶端生长',
     'photosynthetic electron transport in photosystem I':'光系统一中光合电子运输',
     'photosynthetic electron transport in photosystem II':'光系统二中光合电子运输',
     'ovule development':'胚珠发育',
     'ovule':'胚珠',
     'development':'发育',
     'negative regulation of':'逆向调控',
     'cyclic':'循环',
     'nucleotide binding':'核苷酸绑定',
     'hypoxia':'缺氧',
     'nucleotide':'核苷酸',
     'gluconeogenesis':'糖异生',
     'mitotic cell cycle':'有丝分裂细胞周期',
     'mitotic recombination':'有丝分裂重组',     
     'mitotic spindle assembly checkpoint':'有丝分裂纺锤体装配检测点',
     'tryptophan':'色氨酸',
     'translational initiation':'翻译初始化',
     'protein deubiquitination':'蛋白质去泛素化',
     'oxidoreductase activity':'氧化还原酶活性',
     'oxidoreductase':'氧化还原酶',     
     'oxidoreduction coenzyme':'氧化还原辅酶',
     'coenzyme':'辅酶',
     'cycle':'周期',
     'Golgi vesicle transport':'高尔基囊泡运输',
     'response to cyclopentenone':'应对环戊',
     'cyclopentenone':'环戊',
     'ncRNA':'不编码RNA',
     'acetyl-CoA':'乙酰辅酶A',
     'fatty acid-CoA':'脂肪酸辅酶A',
     'amino acid':'氨基酸',
     'activity':'活性',
     'activity,':'活性，',
     'meiotic nuclear division':'减数分裂细胞核分裂',
     'meiotic':'减数分裂',
     'autophagy':'自噬',
     'ATPase activity':'三磷酸腺苷酶活性',
     'ATPase':'三磷酸腺苷酶',
     'fructose':'果糖',
     'postreplication repair':'复制后维修',
     'cell cycle':'细胞周期',
     'unsaturated fatty acid':'不饱和脂肪酸',
     'stomatal complex morphogenesis':'气孔综合体成型',
     'stomatal movement':'气孔运动',
     'stomatal':'气孔',
     'morphogenesis':'成型',
     'multicellular organismal development':'多细胞生物体发育',
     'multicellular organism reproduction':'多细胞生物繁殖',
     'multicellular':'多细胞',
     'hexakisphosphate':'六磷酸',
     'inositol':'肌醇',
     'myo-inositol':'myo-inositol???',
     'carbohydrate transmembrane transporter activity':'碳水化合物跨膜运输员活动',
     'drug':'药',
     'transmembrane transporter activity':'跨膜运输员活动',
     'transmembrane transport':'跨膜运输',
     'carbohydrate':'碳水化合物',
     'transmembrane':'跨膜',
     'intracellular':'细胞内',
     'aromatic amino acid family':'芳香族氨基酸',
     'amino acid':'氨基酸',     
     'aromatic':'芳香族',
     'family':'族',
     'protein targeting to vacuole':'作用于液泡蛋白',
     'meristem initiation':'分生组织开始分生',
     'gene silencing by miRNA':'微RNA引起的基因静默',
     'miRNA':'微RNA',
     'purine nucleobase transport':'嘌呤碱基运输',
     'purine nucleobase':'嘌呤碱基',
     'purine':'嘌呤',     
     'receptor protein':'接收蛋白',
     'receptor':'接收员',
     'tyrosine kinase':'酪氨酸激酶',
     'rRNA modification':'rRNA改造',
     'loosening':'松动',
     'phosphatidylglycerol':'磷脂酰甘油',
     'glycerol':'甘油',
     'diacylglycerol':'二酰基',
     'microtubule nucleation':'开始从头合成微管',
     'microtubule':'微管',
     'microtubule':'以微管为基础的',
     'motor':'马达',
     'microsporogenesis':'生成孢子',
     'brassinosteroid':'油菜素内酯',
     'karrikin':'<a title=\"karrikin\">烟熏发芽素</a>',
     'large ribosomal subunit':'大核糖体亚基',
     'proteasome core complex assembly':'蛋白酶体核心综合体组装',
     'proteasome core complex':'蛋白酶体核心复合体',     
     'proteasome':'蛋白酶体',
     'complex':'复合体',
     'determination of bilateral symmetry':'双边对称确定',
     'bilateral':'双边',
     'symmetry':'对称',
     'defense response to fungus, incompatible interaction':'防卫真菌，相互作用冲突',
     'blue light':'蓝光',
     'red light':'红光',
     'far-red light':'红外光',
     'far red light':'红外光',     
     'phragmoplast':'<a title=\"phragmoplast\">成膜体</a>',
     'organ':'器官',
     'virus':'病毒',
     'UV-A':'近紫外线',
     'UV-B':'中紫外线',
     'UV':'紫外线',
     'stromule':'基质填充管',
     'cyclin-dependent':'依赖细胞周期蛋白的',
     'serine/threonine kinase':'丝氨酸/苏氨酸激酶',
     'threonine':'苏氨酸',
     'stomatal lineage progression':'非特定表皮细胞渐变为气孔',
     'anthocyanin accumulation in tissues in response to UV light':'应对紫外线中花青素积累',
     'anthocyanin':'花青素',
     'anthocyanin-containing':'含花青素',
     'compound':'化合物',
     'accumulation':'积累',
     'light':'光',
     'transition metal ion':'过渡金属离子',
     'metal ion':'金属离子',
     'coumarin':'香豆素',
     'positive regulation of':'正向调控',
     'nuclear envelope':'细胞核封套',
     'lignin':'木质素',
     'cellular respiration':'细胞呼吸',
     'respiration':'呼吸',
     'integral component of membrane':'细胞膜关键组成部分',
     'integral component of plasma membrane':'细胞膜疏水区关键组成部分？？？',
     'integral component of':'关键组成部分',
     'regulation of defense response':'调控防卫应答',
     'phenylpropanoid':'苯丙',
     'UDP-glycosyltransferase':'UDP糖基转移酶',
     'signal transducer activity':'信号传感器活动',
     'transducer':'传感器',
     'response to molecule of bacterial origin':'应对源自细菌分子的刺激',
     'protein maturation':'蛋白成熟',
     'maturation':'成熟',
     'flavonoid':'类黄酮',
     'temperature stimulus':'温度刺激',
     'temperature':'温度',
     'cation homeostasis':'阳离子稳态',
     'cation:cation':'阳离子:阳离子',     
     'cation':'阳离子',
     'homeostasis':'稳态',
     'aerobic respiration':'有氧呼吸',
     'aerobic':'有氧',
     'very long-chain':'超长链',
     'long-chain':'长链',     
     'size':'大小',
     'pentacyclic triterpenoid':'五环三萜',
     'presequence translocase':'蛋白质运输机???',
     'auxin polar':'生长素有向',
     'protein import into nucleus':'引入蛋白到细胞核',
     'mitotic nuclear division':'有丝分裂细胞核分裂',
     'glycine':'甘氨酸',
     'assembly or disassembly':'组装或拆卸',
     'disassembly':'拆卸',
     'structural organization':'结构组织',
     'cell-cell signaling':'细胞间通信',
     'stamen':'花蕊',
     'phase change':'阶段改变',
     'translation initiation factor activity':'启动转译因子的活性',
     'initiation':'初始化',
     'factor':'因子',
     'xylem':'木质部',
     'trichoblast':'<a title=\"藻类等生物的毛发凸起\">毛发</a>',
     'phosphorelay response regulatory activity':'应对磷酸中转协调员的活性',
     'outer membrane':'外膜',
     'integral component of mitochondrial outer membrane':'线粒体外膜关键部分',
     'integral component of chloroplast outer membrane':'叶绿体外膜关键部分',
     'mitochondrial outer membrane translocase complex':'线粒体外膜移位酶复合体',
     'translocase':'移位酶',
     'identical':'相似',
     'photosystem II':'光系统二',
     'photosystem':'光系统',     
     'actin filament-based movement':'肌动蛋白丝主导的运动',
     'actin filament':'肌动蛋白丝',
     'actin filament bundle assembly':'肌动蛋白丝束组装',
     'movement':'移动',
     'serine/threonine/tyrosine':'丝氨酸/苏氨酸/酪氨酸',
     'auxin-activated':'由生长素激活的',
     'ER to Golgi':'内质网到高尔基体',
     'polysaccharide':'多糖',
     'multidimensional':'多维',
     'mitochondrial matrix':'线粒体基质',
     'innate immune response':'先天免疫应对',
     'glucose':'葡萄糖',
     'protein modification':'蛋白改造',
     'PSII associated light-harvesting complex II':'与光系统二相关的捕光复合体二',
     'light-harvesting':'捕光',
     'spindle assembly':'纺锤体组装',
     'spindle':'纺锤体',
     'nematode':'线虫',
     'production of ta-siRNAs involved in RNA interference':'制造参与RNA干扰的siRNA',
     'mitochondrial proton-transporting ATP synthase complex':'线粒体内用以运输质子的三磷酸腺苷合成酶复合物',
     'proton':'质子',
     'sugar:proton symporter activity':'糖：质子转运体活性',
     'lateral root':'侧根',
     'other organism':'异物',
     'multi-organism':'多-有机体',
     'protein homodimerization activity':'蛋白 同源二聚体成型??? 活性',
     'nuclear division':'细胞核分裂',
     'cotyledon':'子叶',
     'cotyledon vascular tissue pattern formation':'子叶维管组织成型',
     'calcium-transporting ATPase activity':'负责钙运输三磷酸腺苷酶活性',
     'peroxidase activity':'过氧化物酶活性',
     'polarity specification of adaxial/abaxial axis':'正面轴/背面轴极性确定',
     'peptidyl-prolyl':'肽基脯氨酰基',
     'peptidyl-proline':'肽脯氨酸',
     'peptidyl-cysteine':'肽酰半胱氨酸',
     'cis-trans isomerase activity':'顺反异构酶活性',
     'cis-trans isomerase':'顺反异构酶',
     'hormone-mediated':'荷尔蒙引发的',
     'mediated':'引发的',
     'hormone':'荷尔蒙',
     'carpel':'心皮',
     'small':'小',
     'nucleolar':'核仁',
     'ribonucleoprotein':'核糖核蛋白',
     'sodium ion':'钠离子',
     'sodium:proton antiporter activity':'钠:质子 逆转运蛋白活性',
     'antiporter activity':'逆转运蛋白活性',
     'sodium:proton':'钠:质子',
     'antiporter':'逆转运蛋白',
     'desiccation':'干燥',
     'polyamine':'多胺',
     'MAP kinase activity':'丝裂原激酶活性？？？',
     'MAP kinase kinase activity':'丝裂原激酶活性？？？',     
     'MAP':'丝裂原激发的蛋白？？？',
     'gamma radiation':'伽马辐射',
     'divalent':'二价',
     'lipoate':'硫辛酸共轭碱',
     'xylem and phloem pattern formation':'木质部韧皮部纹路成型',
     'phloem or xylem histogenesis':'韧皮部或木质部组织发生',
     'histogenesis':'组织发生',
     'phloem':'韧皮部',
     'protein sumoylation':'蛋白质小泛素样化',
     'sumoylation':'小泛素样化',
     'pectin':'果胶',
     'pectinesterase':'果胶酶',
     'pectate lyase':'果胶裂解酶',
     'division':'分裂',
     'calmodulin-dependent':'依赖钙调蛋白的',
     'calmodulin':'钙调蛋白',
     'proline':'脯氨酸',
     'para-aminobenzoic acid':'对氨基苯甲酸',
     'ATP-dependent helicase':'依赖三磷酸腺苷的解旋酶',
     'ATP-dependent peptidase':'依赖三磷酸腺苷的肽酶',
     'helicase':'解旋酶',
     'ATP-dependent':'依赖三磷酸腺苷的',
     'polygalacturonase':'多聚半乳糖',
     'petal formation':'花瓣形成',
     'petal development':'花瓣发育',
     'petal':'花瓣',
     'formation':'形成',
     'sepal':'萼片',
     'specification of floral organ identity':'花器官特性规定',
     'maintenance of floral organ identity':'花器官特性保持',     
     'floral organ':'花器官',
     'floral':'花',
     'import':'引入',
     'tRNA':'转移核糖核酸',
     'shoot system':'芽系统',
     'serine-type endopeptidase':'丝氨酸型内肽酶',
     'serine-type':'丝氨酸型',
     'endopeptidase':'内肽酶',
     'polar nucleus fusion':'极核融合',
     'polar nucleus':'极核',
     'fusion':'融合',
     'mismatch repair':'错误匹配维修',
     'insect':'昆虫',
     'hypoxia':'缺氧',
     'modified amino acid':'改造后氨基酸',
     'intra-Golgi':'高尔基体内',
     'callose deposition in cell wall':'细胞壁胼胝质沉积',
     'callose':'胼胝质',
     'deposition':'沉积',
     'karyogamy':'核融合',
     'chiasma':'<a title=\"chiasma\">染色单体链接</a>',
     'anther':'花药',
     'Golgi':'高尔基体',
     'levels':'水平',
     'inhibitor':'抑制剂',
     'generation of precursor metabolites and energy':'产生前体代谢物与能量',
     'sphingoid':'鞘氨醇',
     'sphingolipid':'鞘脂',
     'root epidermal':'根表皮',
     'epidermal':'表皮',
     'mediator complex':'转录引导蛋白复合体',
     'transferase activity, transferring hexosyl groups':'转移酶活性，转移己糖单价基群',
     'translational termination':'结束转译',
     'anion channel':'阴离子通道',
     'anion':'阴离子',
     'organic anion transmembrane transporter activity':'有机阴离子跨膜运输蛋白活性',
     'G2/M transition of mitotic cell cycle':'<a title=\"G2/M\">有丝分裂细胞周期中前有丝分裂向有丝分裂转变</a>',
     'glutathione':'谷胱甘肽',
     'cell plate':'单元板',
     'stroma':'基质',
     'mechanical stimulus':'机械刺激',
     'pollen sperm':'花粉精子',
     'pattern specification process':'定型过程',
     'embryonic pattern specification':'胚胎定型',
     'post-embryonic development':'后期胚胎发育',
     'post-embryonic':'后期胚胎',
     'lipase':'脂肪酶',
     'calcium-mediated':'钙引导的',
     'cysteine-type':'半胱氨酸型',
     'aging':'老化',
     'water channel':'水路',
     'water':'水',
     'channel':'通道',
     'mitochondrial respiratory chain complex II, succinate dehydrogenase complex (ubiquinone)':'线粒体呼吸链复合体二，琥珀酸脱氢酶复合体（泛醌）',
     'succinate':'琥珀酸',
     'dehydrogenase':'脱氢酶',
     'ubiquinone':'泛醌',
     'exocyst':'囊泡运输八聚体蛋白复合体',
     'base-excision repair':'碱基切除维修',
     'DNA-directed RNA polymerase':'DNA指向的RNA聚合酶',
     'DNA-directed DNA polymerase':'DNA指向的DNA聚合酶',
     'polymerase':'聚合酶',
     'topological change':'拓扑变化',
     'primary shoot apical meristem specification':'主芽顶端分生组织确定',
     'maintenance of shoot apical meristem identity':'芽顶端分生组织特性维护',
     'maintenance of root meristem identity':'根分生组织特性维护',
     'maintenance of inflorescence meristem identity':'花序分生组织特性维护',
     'maintenance of DNA repeat elements':'DNA重复元素维护',
     'primary root':'主根',
     'shoot apical meristem':'芽顶端分生组织',
     'oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, 2-oxoglutarate as one donor, and incorporation of one atom each of oxygen into both donors':'氧化还原酶活性（作用于成对受体，通过氧分子的掺入或还原，2-氧化戊二酸作为一个供体，在两个供体中掺入氧原子？？？）',
     'donors':'供体',
     'donor':'供体',
     '2-oxoglutarate':'2-氧化戊二酸',
     'monooxygenase':'单加氧酶',
     'monovalent cation:proton antiporter activity':'单价 阳离子：质子 逆转运蛋白活性',
     'anatomical structure':'解剖结构',
     'anatomical':'解剖',
     'phyllome':'叶丛',
     'GTPase':'三磷酸鸟苷水解酶',
     'Ran':'一种在细胞核孔转移RNA和蛋白的蛋白',
     'S-nitrosylation':'S亚硝基化',
     'oxidation-reduction':'氧化还原',
     'one-carbon':'一碳',
     'heme':'血红素',
     'defense response by callose deposition in cell wall':'通过细胞壁胼胝质沉积的防卫应对',
     'antiporter':'共运输体整合膜蛋白',
     'vesicle docking involved in exocytosis':'胞吐作用中囊泡对接',
     'protein import into nucleus, docking':'蛋白进入细胞核，对接',
     'oxylipin':'脂肪酸氧化天然产物',
     'COP9 signalosome':'构光形态9，具有异肽酶活性的蛋白复合体',
     'triglyceride lipase':'甘油三酯脂酶',
     'triglyceride':'甘油三酯',
     'dehiscence':'裂开',
     'secondary':'二级',
     'lithium ion':'锂离子',
     'cobalt ion':'钴离子',
     'cobalt':'钴',
     'chromosome segregation':'染色体分离',
     'FK506 binding':'23元大环内酯FK506绑定',
     'telomere maintenance':'端粒保养',
     'induced systemic resistance, jasmonic acid mediated signaling pathway':'诱发全局抵抗，茉莉酸引导信道',
     'induced systemic resistance, ethylene mediated signaling pathway':'诱发全局抵抗，乙烯引导信道',
     'induced systemic resistance':'诱发全局抵抗',
     'dolichol':'多萜醇',
     '1-phosphatidylinositol-4-phosphate 5-kinase':'1磷脂酰肌醇4磷酸盐 5激酶',
     'wax':'蜡',
     'sulfate assimilation':'硫酸同化',
     'assimilation':'同化',
     'sulfate starvation':'硫酸剥夺',
     'starvation':'剥夺',
     'acting on a sulfur group of donors,':'作用于硫供体群，',
     'disulfide as acceptor':'以二硫化物作为受体',
     'disulfide isomerase':'二硫化物异构酶',
     'disulfide':'二硫化物',
     'isomerase':'异构酶',
     'microbial phytotoxin':'微生物植物毒素',
     'arsenic-containing substance':'含砷物质',
     'trisphosphate':'三磷酸肌醇',
     'inositol trisphosphate':'肌醇三磷酸',
     'abscission':'脱落',
     'potassium ion':'钾离子',
     'cell fate':'细胞命运',
     'commitment':'安排',
     'vitamin':'维他命',
     'symbiotic fungus':'共生真菌',
     'ozone':'臭氧',
     'molecule of fungal origin':'源自真菌分子',
     'nucleotide-sugar':'核苷酸-糖',
     'long-day photoperiodism, flowering':'长日照光周期现象，开花',
     'hydrolase activity, acting on glycosyl bonds':'水解酶活性，作用于糖基键',
     'D-xylose':'丁-木糖',
     'phosphate':'磷酸盐',
     'redox':'氧化还原',
     'nitrogen':'氮',
     'catalase':'过氧化氢酶',
     'transmembrane receptor protein serine/threonine kinase activity':'跨膜接收蛋白 丝氨酸/苏氨酸激酶活性',
     'transmembrane receptor protein kinase activity':'跨膜接收蛋白激酶活性',
     'hydroxylation to 4-hydroxy-L-proline':'羟化为4-羟基-L-脯氨酸',
     'hydroxylation':'羟化',
     '4-hydroxy-L-proline':'4-羟基-L-脯氨酸',
     'clathrin vesicle coat':'网格蛋白囊泡衣',
     'clathrin':'网格蛋白',
     'phospholipid':'磷脂',
     'phospholipase D':'磷脂酶丁',
     'methyl-CpG':'甲基化CpG',
     'male meiosis':'雄性减数分裂',
     'lateral root formation':'侧根形成',
     'isoprenoid':'异戊二烯',
     'covalent chromatin modification':'共价染色质改造',
     'ribonuclease III':'核糖核酸三',
     'nuclease':'核酸',
     'P-P-bond-hydrolysis-driven':'由水解磷酸键驱动的？？？',
     'reactive oxygen species':'活性氧种类',
     'purine nucleobase':'嘌呤碱基',
     'sporopollenin':'孢粉',
     'removal of superoxide radicals':'超氧化物自由基移除',
     'superoxide':'超氧化物',
     'receptor activity':'接受体活性',
     'proton-transporting ATP synthase activity, rotational mechanism':'线粒体内用以运输质子的三磷酸腺苷合成酶活性，旋转机制',
     'secretion':'分泌',
     'preprophase band':'早前期带',
     'double fertilization forming a zygote and endosperm':'双受精形成受精卵和胚乳',
     'zygote':'受精卵',
     'endosperm':'胚乳',
     'cytoplasmic mRNA processing body':'细胞质通信RNA处理体',
     'cytoplasmic':'细胞质',
     'DNA unwinding involved in DNA replication':'DNA复制过程中DNA结构展开',
     'ATP synthesis coupled proton transport':'三磷酸腺苷合成并发质子传输',
     'nutrient reservoir activity':'营养积蓄活动',
     'lyase':'裂解酶',
     'somatic cell DNA recombination':'体细胞DNA重组',
     'regulation of pollen tube growth':'调控花粉管生长',
     'pyruvate kinase activity':'丙酮酸激酶活性',
     'protein import into chloroplast stroma':'叶绿体基质引入蛋白',
     'nucleosome assembly':'核小体组装',
     'lignan':'木脂素',
     'histone deacetylase activity':'组蛋白去乙酰化酶活性',
     'deacetylase':'去乙酰化酶',
     'acetylation':'乙酰化',
     'fucosyltransferase':'岩藻糖转移酶',
     'fruit development':'果发育',
     'defense response signaling pathway, resistance gene-dependent':'依赖抵抗基因的信道防卫应答',
     'defense response signaling pathway, resistance gene-independent':'不依赖抵抗基因的信道防卫应答',     
     'DNA-directed RNA polymerase IV complex':'DNA引导的四号RNA聚合酶复合体',
     'DNA-directed RNA polymerase V complex':'DNA引导的五号RNA聚合酶复合体',
     'DNA-directed RNA polymerase II, core complex':'DNA引导的二号RNA聚合酶核心复合体',
     'autoubiquitination':'自动泛素化',
     'potassium ion':'钾离子',
     'potassium':'钾',
     'SNAP receptor activity':'囊泡融合蛋白活性',
     'MAPK':'有丝分裂原激活的蛋白激酶',
     'chloroplast nucleoid':'叶绿体类核',
     'apical plasma membrane':'根尖质膜',
     'CCAAT-binding factor complex':'CCAAT结合因子复合体',
     'pseudouridine synthase activity':'伪尿嘧啶合成酶活性',
     'pseudouridine':'伪尿嘧啶',
     'cellular process':'细胞进程',
     'organ senescence':'器官衰老',
     'senescence':'衰老',
     'lead ion':'铅离子',
     'lead':'铅',
     'fatty-acyl-CoA':'脂肪酸酰基辅酶',
     'ammonium transport':'氨运输',
     'N-acetyltransferase activity':'N乙酰转移酶活性',
     'acetyltransferase':'乙酰转移酶',
     'ubiquitin-specific protease activity':'针对泛素的蛋白酶活性',
     'lumen':'流明',
     'RNA-directed':'RNA指导的',
     'DNA topoisomerase type II (ATP-hydrolyzing) activity':'DNA二类拓扑异构酶（三磷酸腺苷水解）活性',
     'quercetin':'槲皮素',
     'translation elongation factor activity':'多肽合成中核糖体链延展',
     'elongation':'延展',
     'serine-type peptidase activity':'丝氨酸类肽酶活性',
     'peptidase':'肽酶',
     'phosphate ion':'磷酸根离子',
     'phosphate starvation':'剥夺磷',
     'metalloendopeptidase':'金属内肽酶',
     'leaf vascular tissue pattern formation':'叶子维管成型',
     'vascular':'维管',
     'inward rectifier':'内向整流',
     'rectifier':'整流',
     'regulation of translation':'调控翻译',
     'positive regulation of heterochronic development':'正调控异时发育',
     'coactivator':'协同活化蛋白',
     'microgametogenesis':'微配子发生',
     'megagametogenesis':'巨配子发生',
     'somatic embryogenesis':'体胚胎发生',
     'developmental process':'发育进程',
     'boron-containing substance deprivation':'去除含硼物质',
     'intracellular signal transduction':'细胞内信号转导',
     'singlet oxygen':'单氧',
     'acidic':'酸性',
     'neutral':'中性',
     'cofactor':'协同因子',
     'gynoecium':'雌蕊',
     'transcription regulatory region DNA binding':'转录调控区DNA绑定',
     'sexual reproduction':'有性生殖',
     'photoprotection':'光保护',
     'nucleotide-excision repair':'核苷酸切除维修',
     'excision':'切除',
     'eukaryotic translation initiation factor 2B complex':'真核转译启动因子2B复合体',
     'eukaryotic':'真核',
     'cytochrome-c oxidase activity':'细胞色素复合体氧化酶活性',
     'NAD(P)H dehydrogenase complex (plastoquinone)':'脱氢酶复合体（质体醌）-- 电子转移链中的一环',
     'ion':'离子',
     'pollen tube guidance':'花粉管向导',
     'ESCRT III complex':'运输所需的3号核内体排序复合体',
     'ESCRT':'运输所需的核内体排序复合体',
     'xyloglucan':'木葡聚糖',
     'sucrose':'蔗糖',
     'heterochromatin':'杂染色质',
     'camalexin':'吲哚生物碱',
     'beta-galactosidase':'β半乳糖苷',
     'galactosidase':'半乳糖苷',
     'alkaloid':'生物碱',
     'L-ascorbic acid':'L抗坏血酸',
     '(1->3)-beta-D-glucan':'β(1-3)葡聚糖',
     '1,3-beta-D-glucan':'1，3 β葡聚糖',
     'ubiquitin protein ligase':'泛素蛋白连接酶',
     'protein self-association':'蛋白自交互',
     'polygalacturonate 4-alpha-galacturonosyltransferase':'聚半乳糖 4-α-半乳糖醛酸转移酶',
     'polygalacturonate':'聚半乳糖',
     'metallopeptidase':'金属肽酶',
     'damaged':'破损',
     'Tic complex':'叶绿体内膜负责移位蛋白复合体',
     'hexamerization':'六聚',
     'ionizing radiation':'电离辐射',
     'ionizing':'电离',
     'resolution of meiotic recombination intermediates':'减数分裂重组中间产物分解',
     'resolution':'分解',
     'regulation of reactive oxygen species metabolic process':'调控活性氧类的新陈代谢过程',
     'porphyrin-containing compound':'含卟啉化合物',
     'male gamete generation':'生成雄配子',
     'gamete':'配子',
     'generation':'生成',
     'Mo-molybdopterin cofactor':'钼钨催化剂辅因子',
     'reproduction':'生殖',
     'fungus':'真菌',
     'basipetal':'巴斯花瓣',
     '4-coumarate-CoA':'4香豆酸辅酶A',
     'suberin':'木栓质',
     'single-stranded':'单链',
     'targeting':'瞄准',
     'phosphorylative mechanism':'磷酸化机制',
     'hydrogen-exporting ATPase activity,':'输出氢三磷酸腺苷酶活性，',
     'hexokinase':'己糖激酶',
     'hexokinase-dependent':'依赖己糖激酶的',
     'fructokinase':'果糖激酶',
     'endomembrane':'内膜',
     'glucokinase':'葡萄糖激酶',
     'oomycetes':'卵菌',
     'Group II intron splicing':'第二组内含子剪接',
     'intron':'内含子',
     'splicing':'剪接',
     'Cajal body':'卡哈尔体',
     'shade avoidance':'避荫',
     'rhamnogalacturonan':'鼠李糖半乳糖醛酸',
     'II':'二',
     'nucleocytoplasmic':'核蛋白胞质',
     'endosome membrane':'内体膜',
     'endosomal transport':'胞内运输',
     'aminoacyl-tRNA ligase activity':'氨酰基tRNA连接酶活性',
     'catalytic core':'催化核',
     'aminoacylation':'氨酰化',
     'for':'为了',
     '------':'--------',
     'basic':'基本',
     'nuclear':'细胞核',
     'nuclear dicing body':'圆核小体',
     'galactolipase':'半乳糖',
     'phosphatidylcholine':'磷脂酰胆碱',
     '1-acylhydrolase':'1乙酰水解酶',
     'acylhydrolase':'乙酰水解酶',
     'decarboxylase':'脱羧酶',
     'nucleoplasm':'核质',
     'inflorescence':'花序',
     'histone':'组蛋白',
     'proliferation':'增殖',
     'modification':'改造',
     'sulfur':'硫',
     'sulfur compound':'硫化物',
     'phosphorylation':'磷酸化',
     'growth':'生长',
     'promoter':'转录启动带',
     'maltose':'麦芽糖',
     'DNA-dependent':'依赖DNA的',
     'response to':'应对',
     'post-translational':'转译后期',
     'relocation':'重定位',
     'cytokinin':'细胞分裂素',
     'water':'水',
     'red or far-red light':'红光或红外线',
     'spermidine':'亚精胺',
     'synthase':'合成酶',
     'hydrogenase':'氢化酶',
     'reductase':'还原酶',
     '7-hydroxymethyl':'7-羟甲基',
     'hydroxymethyl':'羟甲基',
     'chitinase':'几丁质酶',
     'thiamine':'硫胺素',
     'riboflavin':'核黄素',
     'ribonuclease':'核糖核酸',
     'primary':'主',
     'phylloquinone':'叶绿醌',
     'catalytic':'催化',     
     'magnesium':'镁',
     'chelatase':'螯合酶',
     'channel':'通道',
     'ligand-gated':'配体闸门',
     'demethylation':'去甲基化',
     'de-etiolation':'脱黄化',
     'cortical':'皮质',
     'coat':'衣',
     '1-aminocyclopropane-1-carboxylate':'1-氨基环丙烷-1-羧酸酯',
     'transaminase':'转氨酶',
     'reproductive':'生殖',
     'poly(U)':'多聚尿苷酸'
}

def file_to_lst(filename):
   f = open(filename)
   lst = f.readlines()
   f.close()
   return lst


def make_gene_name_dict(file):
   d = {}
   f = open(file)
   for line in f:
      lst = line.split('\t')
      gene = lst[0]
      name = d.get(gene, '')
      name += ' '.join(lst[1:]).strip() + ';'
      d[gene] = name
   f.close()
   return d


def convert_to_locus(gene, filename):
   gene = gene.strip().lower()
   if gene == '':
      return 'NONE'
   f = open(filename)
   for line in f:
      lst = line.split('\t')
      locus = lst[0]
      short_name = lst[1].strip().lower()
      short_name_lst = short_name.split()
      long_name = lst[2].strip().lower()
      long_name_lst = long_name.split()
      gene_lst = gene.split()
      n = len(gene_lst)
      count1 = 0
      count2 = 0
      for x in gene_lst:
         if x in short_name_lst:
            count1 += 1
         if x in long_name_lst:
            count2 += 1
      if count1 == n or count2 == n:
         return locus
         
   return 'NONE'


def get_gene_name(gene, file):

   name = ''
   f = open(file)
   count = 0
   for line in f:
      lst = line.split('\t')
      if gene == lst[0]:
         name += ' '.join(lst[1:]).strip() + ';'
         count += 1
      if count > 10:
         break
   f.close()
   return name


# word is an annotation
def translate_one_word(word):
   if word in d:
      return d[word]
   else:
      #for x in word.split():
      #   x = x.strip()
      #   if x in d:
      #      t += d[x] +  ' '
      #   else:
      #      t += x + ' '
      for k in range(5): # number of passes in translating

         translate_len = []
         translate_lst = []
         lst = word.split()
         n = len(lst)
         for i in range(n):
            found = 0
            for j in range(n,i,-1):
               s = ' '.join(lst[i:j])
               if s in d:
                  found = 1
                  translate_len.append(j-i)
                  translate_lst.append(' '.join(lst[:i]) + ' ' + d[s] + ' ' + ' '.join(lst[j:]))
                  break
         if len(translate_lst) > 0:
            index = translate_len.index(max(translate_len))
            word =  translate_lst[index]
         else:
            return word

      return word

def translate_words(word_lst):
   lst = []
   for x in word_lst:
      lst.append(translate_one_word(x))
   return lst

def find_gene_annotation(gene, lst):
   
   p = []
   c = []
   f = []
   for x in lst:
      L = x.strip().split('\t')
      t = L[7]
      a = L[4]
      if L[0] == gene:
         if t  == 'P' and not a in p:
            p.append(a)
         elif t == 'C' and not a in c:
            c.append(a)
         elif t == 'F' and not a in f:
            f.append(a)
   s = ''
   if p:
      s += '<br/><b>生物过程</b><br/>' + '<br/>'.join(translate_words(p)) + '<br/>'
   if f:
      s += '<br/><b>分子功能</b><br/>' + '<br/>'.join(translate_words(f)) + '<br/>'
   if c:
      s += '<br/><b>所在位置</b><br/>' + '<br/>'.join(translate_words(c)) + '<br/>'
   return s


def find_genes_with_description(desc, lst):

   result_d = {}
   desc_lst = desc.split()
   for x in lst:
      L = x.strip().split('\t')
      t = L[7]
      a = L[4]
      a_lst = a.split()
      a_lst = [x.lower() for x in a_lst] # convert each element to lower case
      g = L[0]
      count = 0
      for y in desc_lst:
         if y in a_lst:
            count += 1
      if count == len(desc_lst):
         t = result_d.get(g, '')
         if t.find(a) == -1:
            t +=  a + '; '
         result_d[g] = t 

   return result_d

def in_locus(gene, content):
   for x in content:
      if gene == x.split('\t')[0]:
         return True
   return False

print("Content-type: text/html; charset=utf-8")
print("")

form = cgi.FieldStorage()
gene = ''
description = ''
if 'gene_name' in form:
   gene = form['gene_name'].value
   gene = gene.strip().upper()
if 'gene_function' in form:
   description = form['gene_function'].value
   description = description.strip().lower()
content = file_to_lst('ATH_GO_GOSLIM.txt')
invalid_gene = False
if gene == '':
   invalid_gene = True
if invalid_gene  and description == '':
   print("无效基因 %s<br/>" % gene)
   exit()
if not in_locus(gene, content):
   locus = convert_to_locus(gene, 'gene_aliases_20140331.txt')
   if locus != 'NONE':
      gene = locus
   else:
      invalid_gene = True



result = ''
if not invalid_gene:
   result = find_gene_annotation(gene, content)
   gene_name = get_gene_name(gene, 'gene_aliases_20140331.txt')

print("<!DOCTYPE html>")
print("<html>")
print("<head><title>%s  %s</title></head>" % (gene, description))
print("<body>")
if result != '':
   print("<p>基因：%s<br/>名字：%s</p>" % (gene, gene_name))
   print("%s" % result)
   print("<br/>")    
elif not invalid_gene:
   print("找不到。")


if description != '':
   gene_annot_d = find_genes_with_description(description, content)
   if gene_annot_d:
      print("<p><b>有%s功能的基因</b></p>" % (description))
   else:
      exit()
   d = make_gene_name_dict('gene_aliases_20140331.txt')
   for x in gene_annot_d:
      g = x
      a = gene_annot_d[g]
      gn = d.get(g, '?')
      print("%s (%s) |  %s<br/>" % (g, gn, a))

print("</body>")
print("</html>")
      
      
